services:
    bastien59960.stats.collect.controller:
        class: bastien59960\stats\controller\collect_controller
        arguments:
            - '@dbal.conn'
            - '@request'
            - '@user'
            - '@config'
            - '%core.table_prefix%'

    bastien59960.stats.acp.controller:
        class: bastien59960\stats\controller\acp_controller
        arguments:
            - '@dbal.conn'
            - '@template'
            - '@request'
            - '@user'
            - '@config'
            - '%core.table_prefix%'

    bastien59960.stats.listener:
        class: bastien59960\stats\event\listener
        arguments:
            - '@dbal.conn'
            - '@request'
            - '@user'
            - '@config'
            - '@template'
            - '@controller.helper'
            - '%core.table_prefix%'
        tags:
            - { name: event.listener }

    bastien59960.stats.cron.geo_async:
        class: bastien59960\stats\cron\task\geo_async
        arguments:
            - '@dbal.conn'
            - '@config'
            - '%core.table_prefix%'
        calls:
            - [set_name, [cron.task.bastien59960.stats.geo_async]]
        tags:
            - { name: cron.task }
